### ISSUE TITLE
charge with already added card

### ISSUE THREAD

**Issue by musman92** [cartalyst/stripe#109]
suppose i add many card for one customer then how we charge customer with selected card?

**Comment by TechTailor** [comment]
Hey, 

When you create a charge, the default card (on the stripe account for that user) will be charged automatically, if there is no card stored for that user, you will need to provide one otherwise an error will be thrown -

`$charge = $stripe->charges()->create([
    'customer' => 'cus_4EBumIjyaKooft',
    'currency' => 'USD',
    'amount'   => 50.49,
]);` 

In case of a user having multiple cards, just pass the card_id in the source parameter -

`$charge = $stripe->charges()->create([
    'customer' => 'cus_4EBumIjyaKooft',
    'currency' => 'USD',
    'amount'   => 50.49,
    'source' => 'card_4Ebawd232dawd',
]);`

That should do the trick. If you come across any issues, do feel free to ask. 

-Cheers

**Comment by brunogaspar** [comment]
Thanks for the explanation @TechTailor
