### ISSUE TITLE
[2.x] Null Parameter Bug

### ISSUE THREAD

**Issue by GrahamCampbell** [cartalyst/stripe#153]
It's not possible to unset a customer's address, because the way to do this is to explicitly pass a null parameter. Unfortunately, when `http_build_query` is called, this parameter gets removed.

Broken example code, which results in no parameters being sent:

```php
/** @var Cartalyst\Stripe\Api\Customers $customers */
$customers->update($customerId, ['address' => null]);
```

**Comment by GrahamCampbell** [comment]
Ok, so replacing `null` with the empty string seems to work. D'no if we should just say that the correct thing to do is to use the empty string, or if we should do something to fix this. Though, we might not want to automatically convert null parameters to empty strings... will likely break other things.

**Comment by brunogaspar** [comment]
Will try something out, thanks for the report.

**Comment by brunogaspar** [comment]
From what i could test, converting `null` to empty string `''` is the only decent way.

There's only a few places that requires an array_filter on the library, but other than that, it seems to work as expected.

Even using the `form_params` instead of `query` for POST requests will have this problem if i remember properly, since it uses the http_build_query internally, but again, if i remember properly.

But let me know if you have any other ideas before doing the change.

**Comment by GrahamCampbell** [comment]
Yeh, not sure. Maybe we should only make this change in 3.x, since it's not clear what we might accidentally break? Maybe people are using the behaviour that null stuff is removed?

**Comment by brunogaspar** [comment]
I don't mind to have this fixed on 2.3 and 2.4 but of course the safest way is on 3.x since this is a bug fix but is also a breaking change.

So, i guess i'll leave it as is for now on the 2.x versions and push the fix for 3.x.

**Comment by GrahamCampbell** [comment]
Sure. Anyone wanting to work around the current behaviour can just set the empty string in place of null, in their own code. This is what I have done, and that works fine in 2.4.0, and will also work in 3.x.

**Comment by brunogaspar** [comment]
I have this fixed locally on the 3.x branch, will push this soon as a separate commit to that branch.

**Comment by GrahamCampbell** [comment]
Cool. 👍
