### ISSUE TITLE
Any advantage over the official package?

### ISSUE THREAD

**Issue by mokhosh** [cartalyst/stripe#191]
Sorry to ask a question in the issues section, but I didn't see a discussion section on this repo. I also googled this but didn't find anything.

So, are there any advantages in using this package over the official one? I couldn't find anything radically different in the API, and of course the official package has the advantage of being official.

**Comment by mokhosh** [comment]
Thank you @brunogaspar That fully answers my question (and the three people who showed interest by liking the question)

**Comment by levacic** [comment]
Not to sound negative, I liked the question because I was honestly curious about any features offered by this package that aren't offered by Stripe's official one these days.

My assumption is that when it was initially released, it might have actually offered either a nicer API, or some features missing from the official one, or integrations with frameworks, etc. - and as people still might be using it, well, it's still being maintained to a degree to preserve functionality for those users.

**Comment by GrahamCampbell** [comment]
If you look at the source code of the two packages, the main difference is obvious: Stripe's package design is poor, clearly not written by PHP professionals. This package uses OOP properly and uses the rock-solid Guzzle HTTP client under the hood.

**Comment by brunogaspar** [comment]
Sorry guys, i genuinely understand the question (which is a fair one) but i personally prefer to use the issues for bugs, library usage that might not be documented, feature requests and in this case missing Stripe APIs.

But regardless, i could give a fully fledged opinion, however, i haven't looked into the official library in such a long time that i don't really know the state of it, so i don't think i would give a very honest and up to date response.

What i can say is that, this library was created to be more OOP friendly and a tad more modern i guess, to have a better code base (i remember the official one was not that elegant), use better dependencies underneath like Guzzle for example, you can for example use the API you want (like the Customers one) instead of going through the main `Stripe` class and call the `customers()` method...

The main benefit i see on using the official one is that they will get the APIs on the library first, since they work (i assume) for Stripe itself and know about that stuff before everyone else :)

Some might agree, some might not agree, best way is to source dive and see how stuff is done and try to determine for yourself if it's good/bad :)

If needed, you can always contact me directly.

Thanks!

**Comment by brunogaspar** [comment]
Well, @GrahamCampbell kinda beat me to it lol

Thanks @GrahamCampbell !

**Comment by levacic** [comment]
Thanks for the explanation @brunogaspar!

Yeah, Stripe uses cURL by default, although they do provide an interface to which you can implement a Guzzle-based client if you wish to do so. A lot of their code is auto-generated, though, and people might have strong opinions on that. But this doesn't seem uncommon for PHP SDKs, and it's true that many companies might not actually have experienced PHP developers on their team when their core stack might be based on other technologies.

My personal rule of thumb is that for service integration libraries like these, I'd generally lean towards official ones, unless there's a very clear argument for using something else - because if nothing else, the official package maintainers at least theoretically have a very direct financial interest in providing good support, quick bug resolution, etc. Not to say that this package doesn't do that, but I do understand that doing open source for free can be very exhausting at times.

Either way I appreciate Cartalyst's contributions to the ecosystem, and thank you for the effort put into your packages!

**Comment by mokhosh** [comment]
Thanks @GrahamCampbell that did help.

@brunogaspar Thank you for the explanation. Again, sorry to post this in the issues, I would post it in discussions if it was enabled on the repo.

@levacic Same. Maybe if I find the time to review the sources and I throw up while reading Stripe's code I'll change my mind, but for now I only care about functionality.
