### ISSUE TITLE
Customer Subscriptions

### ISSUE THREAD

**Issue by masitings** [cartalyst/stripe#203]
Hi There,

I would ask about the subscriptions, is there any way to change the subscription that bound to the user in to another user ? My case is i would like to transfer the account to another user, in this case it needs to change the payment and subscription customer also.

**Comment by brunogaspar** [comment]
Hey

Can you elaborate a bit more on what you mean by "transfer the account to another user"?

**Comment by masitings** [comment]
So let say i have account with the plan subscription that has started last month and at this moment id like to transfer my subscription to another user which is im no longer the holder of that account. Id like to move the payment and all the things to the new user.

**Comment by brunogaspar** [comment]
I don't think you can do that, at least not exactly how you want, since Stripe itself does not have (i believe) the ability to transfer those "objects" to different accounts.

What you can probably do instead, and this is without knowing how you track which user belongs to a Stripe customer, is, when you want to perform this transfer from one user to another, you basically set the Stripe customer of the old user to be the Stripe customer of the new user, and perhaps create a brand new Stripe customer just for data integrity and keep your code consistent, if needed of course.

Does it make sense?

Otherwise, you're obviously free to look around their API spec https://stripe.com/docs/api/ and determine if there's a way to perform such task, which i honestly doubt of being possible, but i personally never had the need for it so i can be totally wrong :)

**Comment by masitings** [comment]
Truely make sense man,. Well i guess it possible to change the customer data in subscription instead of change the customer in subscription. 

Thank you very much, i really appriciate your time man.

**Comment by brunogaspar** [comment]
No problem. Let me know if you get stuck or need help on anything else in this regard, happy to help.

Have fun :)
