### ISSUE TITLE
Cartalyst\Stripe\Utility::convertToNumber doesn't work for 17.99

### ISSUE THREAD

**Issue by winglian** [cartalyst/stripe#35]
This is mostly because PHP doesn't juggle floats to int well. But there should be a way to input the cents directly as I'm sure there are other edge cases such as 

`(int) (17.99 * 100) == 1798`

**Comment by brunogaspar** [comment]
It's because of the `(int)` casting.

**Comment by winglian** [comment]
@brunogaspar I know that. I'm opening this bug because Cartalyst REQUIRES that we use the USD format of 17.99 and DOESN'T allow us to pass in cents (1799) and bypass the Cartalyst\Stripe\Utility::prepareParameters() method.

**Comment by brunogaspar** [comment]
Ya, will have a look next week.

**Comment by brunogaspar** [comment]
I've actually went ahead and did some changes.

Pushed to the [feature/fix-amount-converter](https://github.com/cartalyst/stripe/tree/feature/fix-number-converter) branch with some tests on this commit https://github.com/cartalyst/stripe/commit/2a3c1747cb211146dcc8017d97c9e7582b4f13d5.

Let me know your thoughts and if it works as expected now.

**Comment by brunogaspar** [comment]
@winglian I had to kinda revert my changes here. You're still able to pass cents, but in a different way, you need to pass them as `0.50` for example.

The reason is that this is breaking applications that kinda allows amounts like 100 dollars to be passed, with this change the 100 was being converted into cents, which is wrong.

Unfortunately that's the only way i could figure out.

Hope that you understand.

This is not tagged or merged into the 1.0 branch, will do the merge of this either tomorrow (friday) or monday morning and then the tag of it itself.
