### ISSUE TITLE
Guzzle 6 Support

### ISSUE THREAD

**Issue by GrahamCampbell** [cartalyst/stripe#48]
Since there is no open issue regarding this, I think it probably makes sense to open one to allow discussion around this topic.

----

NB https://github.com/cartalyst/stripe/tree/feature/guzzle-6

**Comment by brunogaspar** [comment]
What's to discuss?

**Comment by darnold** [comment]
I think he's referring to the fact that if you try to run composer update with cartalyst/stripe-laravel you get errors for guzzle saying "~5.2 no matching package found".

**Comment by GrahamCampbell** [comment]
> I think he's referring to the fact that if you try to run composer update with cartalyst/stripe-laravel you get errors for guzzle saying "~5.2 no matching package found".

No I'm not?

**Comment by GrahamCampbell** [comment]
It's obvious the master branch doesn't support guzzle 6, and that there's another branch that's partially completed that does.

**Comment by darnold** [comment]
Ah sorry about that. I assumed that's what you were referring to since currently when I try to install cartalyst/stripe-laravel I was getting an error about the guzzle version.  I assume this is because i'm already requiring guzzle 6 in my composer json. Isn't that why you would want the guzzle version bump?

**Comment by GrahamCampbell** [comment]
> Isn't that why you would want the guzzle version bump?

Ultimately, I guess, yes.

**Comment by brunogaspar** [comment]
Didn't meant to close this.

So, the state of things on the feature branch is that the tests are not passing on the following, Products, Orders and SKUs APIS.

The reason they don't pass is because the arrays that are being passed are not valid for Stripe, due to stuff like [this](https://github.com/cartalyst/stripe/blob/feature/guzzle-6/tests/FunctionalTestCase.php#L75).

I can't seem to figure out a way to fix this on Guzzle 6 so far which kinda sucks.

I'm at the point that i'm really willing to ditch Guzzle altogether (was/still is my initial though for v2.0 anyway) if a solution is not found this week.

If someone has a fix or even fixes, please do create a PR.

**Comment by brunogaspar** [comment]
So, i pushed a few fixes, and this, which is [kind of an hack](https://github.com/cartalyst/stripe/commit/38748d239a54f9d57778495e7f12431470cab642#diff-955e3aab4c4bf4183207ed96f1374489R47) to be honest, but it's better than nothing i believe.

Tests are [all green](https://travis-ci.org/cartalyst/stripe/builds/101509585) now, which are very good news.

Please let me know if you guys have a better way to handle this and/or improvements to the rest of the code, so i can ship it.

**Comment by brunogaspar** [comment]
I'm scheduling this to be merged into master and tagged on monday unless someone has feedback or something that requires changes.
