### ISSUE TITLE
Question: Calls for Managed Accounts.

### ISSUE THREAD

**Issue by MPJHorner** [cartalyst/stripe#74]
I can't seem to find any documentation about making calls for managed accounts.
I can make calls for other accounts using my API. The documentation shows how this can be done like below...
(As CURL - With Headers)
```
curl https://api.stripe.com/v1/charges/{CHARGE_ID}/refunds \
   -u {PLATFORM_SECRET_KEY}: \
   -H "Stripe-Account: {CONNECTED_STRIPE_ACCOUNT_ID}" \
   -d amount=1000
```
(Using Stripe PHP Lib)
```php
\Stripe\Customer::create(
  array("description" => "example@stripe.com"),
  array("stripe_account" => CONNECTED_STRIPE_ACCOUNT_ID)
);
```

I'm trying to get this working using Laravel 5.2

I have tried the following, but seems to ignore the param.
```php
Stripe::transfers()->all([],[
    'stripe_account' => $stripe_id
]);
```

Many thanks!

**Comment by brunogaspar** [comment]
Will have a look into adding a method to allow the account id to be passed like so

```php
Stripe::accountId(:account-id-here)->transfers()->all();
```

**Comment by brunogaspar** [comment]
@MPJHorner Have a look and see if it works as expected.
Please do note that you'll need to define a `null` accountId if you want to manage your main account after you used a managed account (kindly look at the tests for the example).
Otherwise you'll need to create a different instance of the object so it doesn't get interference.

I'll look into addressing this stuff a bit better for v3.
