### ISSUE TITLE
2.0 branch is actually 2.1

### ISSUE THREAD

**Issue by GrahamCampbell** [cartalyst/stripe#91]
Mistake?

**Comment by brunogaspar** [comment]
Kind of a mistake on my end, the latest tag should've been `2.0.10` instead of `2.1.0`.

While we follow semver the best as we can, it's quite difficult to have it well applied here, since Stripe has a versioning system in place that doesn't help much.

I'll have a look into this later in the week, thanks for pointing it out!

**Comment by GrahamCampbell** [comment]
@brunogaspar The 2.0 branch is still containing 2.1 code. Should it be renamed to 2.1?

**Comment by brunogaspar** [comment]
Sorry, i forgot about this.

Not entirely sure how to better approach this though but here are some thoughts:
1) Create `2.1` branch till the latest commits of the 2.1.4 release
2) Reset `2.0` branch to the commits before the commits of 2.1 (it's a bit of a breaking change i assume)
3) Leave it as is but create a `2.1` branch regardless
